export const TEAMS = {
  hawks: { id: '1', name: 'Atlanta Hawks', color: '#E03A3E' },
  celtics: { id: '2', name: 'Boston Celtics', color: '#007A33' },
  nets: { id: '17', name: 'Brooklyn Nets', color: '#000000' },
  hornets: { id: '30', name: 'Charlotte Hornets', color: '#1D1160' },
  bulls: { id: '4', name: 'Chicago Bulls', color: '#CE1141' },
  cavaliers: { id: '5', name: 'Cleveland Cavaliers', color: '#860038' },
  mavericks: { id: '6', name: 'Dallas Mavericks', color: '#00538C' },
  nuggets: { id: '7', name: 'Denver Nuggets', color: '#FEC524' },
  pistons: { id: '8', name: 'Detroit Pistons', color: '#C8102E' },
  warriors: { id: '9', name: 'Golden State Warriors', color: '#1D428A' },
  rockets: { id: '10', name: 'Houston Rockets', color: '#CE1141' },
  pacers: { id: '11', name: 'Indiana Pacers', color: '#002D62' },
  clippers: { id: '12', name: 'LA Clippers', color: '#C8102E' },
  lakers: { id: '13', name: 'Los Angeles Lakers', color: '#552583' },
  grizzlies: { id: '29', name: 'Memphis Grizzlies', color: '#5D76A9' },
  heat: { id: '14', name: 'Miami Heat', color: '#98002E' },
  bucks: { id: '15', name: 'Milwaukee Bucks', color: '#00471B' },
  timberwolves: { id: '16', name: 'Minnesota Timberwolves', color: '#0C2340' },
  pelicans: { id: '3', name: 'New Orleans Pelicans', color: '#0C2340' },
  knicks: { id: '18', name: 'New York Knicks', color: '#F58426' },
  thunder: { id: '25', name: 'Oklahoma City Thunder', color: '#007AC1' },
  magic: { id: '19', name: 'Orlando Magic', color: '#0077C0' },
  sixers: { id: '20', name: 'Philadelphia 76ers', color: '#006BB6' },
  suns: { id: '21', name: 'Phoenix Suns', color: '#1D1160' },
  blazers: { id: '22', name: 'Portland Trail Blazers', color: '#E03A3E' },
  kings: { id: '23', name: 'Sacramento Kings', color: '#5A2D81' },
  spurs: { id: '24', name: 'San Antonio Spurs', color: '#C4CED4' },
  raptors: { id: '28', name: 'Toronto Raptors', color: '#CE1141' },
  jazz: { id: '26', name: 'Utah Jazz', color: '#002B5C' },
  wizards: { id: '27', name: 'Washington Wizards', color: '#002B5C' },
};

export const getTeamBySlug = (slug) => TEAMS[slug?.toLowerCase()];
export const getAllTeams = () => Object.entries(TEAMS).map(([slug, data]) => ({ slug, ...data }));
